/* ═══════════════════════════════════════════
   YOUTUBE SHORTS — VERTEX EDUCATION
   To add a new short: copy a line below, change
   the title and url, add a comma. Save & push.
   ═══════════════════════════════════════════ */
const youtubeVideos = [
  { title: "Burning Butane Gas Bubbles", url: "https://www.youtube.com/shorts/MrdR2wDklhk" },
  { title: "Bernoulli's Theorem — Pressure vs Fluid Speed", url: "https://www.youtube.com/shorts/oHYUFwpXAfc" },
  { title: "Draw a Perfect Circle", url: "https://www.youtube.com/shorts/Qy9puQ0p7rk" },
  { title: "Magic of Chemistry", url: "https://www.youtube.com/shorts/3Nmz2VSYu4Q" },
  { title: "Sodium Reacts Vigorously with Acid", url: "https://www.youtube.com/shorts/jfvjDPvrwyU" },
  { title: "Projectile Motion", url: "https://www.youtube.com/shorts/xxDvNEY9oNs" },
  { title: "Bernoulli's Theorem — Ball & Cooker Experiment", url: "https://www.youtube.com/shorts/bR_8U_HzLL8" },
  { title: "Law of Inertia", url: "https://www.youtube.com/shorts/pbCbFZHRrnk" },
  { title: "Charging an Object by Rubbing (Electrostatics)", url: "https://www.youtube.com/shorts/W8ljYLRcsJA" },
  { title: "Calculating 'g' — Acceleration Due to Gravity (Pendulum)", url: "https://www.youtube.com/shorts/SIdwSE3yfP0" },
  { title: "Odonil Fire Test Experiment", url: "https://www.youtube.com/shorts/zdLIsFHK56w" },
  { title: "What is Torque?", url: "https://www.youtube.com/shorts/u-HzMJyrugc" },
  { title: "Pressure vs Surface Area — Egg Experiment", url: "https://www.youtube.com/shorts/Qv296dwVJHk" },
  { title: "The Value of g on Earth (9.8 m/s²)", url: "https://www.youtube.com/shorts/oAtgTIqMks0" },
  { title: "Magic of Science", url: "https://www.youtube.com/shorts/FSA42be46gg" },
  { title: "H2 Gas — Vinegar & Magnesium Reaction", url: "https://www.youtube.com/shorts/5zzhGjoD5G4" },
  { title: "School Project — Eddy Current", url: "https://www.youtube.com/shorts/Y4o8zEDGGHk" },
  { title: "Bernoulli's Theorem", url: "https://www.youtube.com/shorts/tCx5PjRQIbA" },
  { title: "Bernoulli's Theorem — Concept Explained", url: "https://www.youtube.com/shorts/RSkIXh44jMw" },
  { title: "Pascal's Law", url: "https://www.youtube.com/shorts/zcOx7lokBG4" },
  { title: "Pascal's Law — Explained", url: "https://www.youtube.com/shorts/AWf_9PC1ZgQ" },
  { title: "Hydraulic Lift", url: "https://www.youtube.com/shorts/bBeQ4pbHnwg" },
  { title: "Series Connection of Resistors — Class 10", url: "https://www.youtube.com/shorts/VbGxI8Viwcg" },
  { title: "Bleaching Powder — Class 10", url: "https://www.youtube.com/shorts/5v6oR7CiL1I" },
  { title: "Iris & Pupil", url: "https://www.youtube.com/shorts/fS5p7hOY2kA" },
  { title: "Torque — Turning Effect of Force (Class 11)", url: "https://www.youtube.com/shorts/KlDOUiWNRDU" },
  { title: "Rheostat — Variable Resistance Device", url: "https://www.youtube.com/shorts/jcGDPAFaHLA" },
  { title: "Torque — Turning Effect of Force", url: "https://www.youtube.com/shorts/s1FBJt9hVhw" },
  { title: "Rheostat — Variable Resistance in Circuit", url: "https://www.youtube.com/shorts/eYrjVwhd6IU" },
  { title: "Conservation of Angular Momentum (Class 11)", url: "https://www.youtube.com/shorts/F2352PpcZ8Q" },
  { title: "Total Internal Reflection", url: "https://www.youtube.com/shorts/e_kUoDVHSfc" },
  { title: "Magnesium Experiment — Inert Oxide Removal", url: "https://www.youtube.com/shorts/7XcM_nq5Zww" },
  { title: "Hydrogen Gas (Dihydrogen)", url: "https://www.youtube.com/shorts/rTPqopJmg6I" },
  { title: "Burning of Magnesium Ribbon", url: "https://www.youtube.com/shorts/bRxQFpwGIL0" },
  { title: "Refractive Index — Glass vs Oil", url: "https://www.youtube.com/shorts/g2LM9DLPLUc" },
  { title: "Capacitor", url: "https://www.youtube.com/shorts/ajorEmFnaco" },
  { title: "How Capacitors Work", url: "https://www.youtube.com/shorts/f8D8DQgprqg" },
  { title: "Reaction of Metal with Acid", url: "https://www.youtube.com/shorts/Nnu-hoGB_CM" },
  { title: "Law of Inertia — Experiment", url: "https://www.youtube.com/shorts/ipnBvw0RpJs" },
  { title: "Bernoulli's Principle", url: "https://www.youtube.com/shorts/TCgmz6KpDzw" },
  { title: "Cool Science Experiment", url: "https://www.youtube.com/shorts/iScEsVBij58" },
  { title: "Burning of Natural Gas (Butane)", url: "https://www.youtube.com/shorts/2BNd6AI33A0" },
  { title: "Non-Polar Solvent Experiment", url: "https://www.youtube.com/shorts/4Sj9NWeYoJo" },
  { title: "Rainbow Formation", url: "https://www.youtube.com/shorts/SVkWoaATgYc" },
  { title: "Electrolysis of Water", url: "https://www.youtube.com/shorts/WWfC02AQm8I" },
  { title: "Plasma Experiment", url: "https://www.youtube.com/shorts/FNXVCtXyjyg" },
  { title: "Magic of Science — Petrol Experiment", url: "https://www.youtube.com/shorts/4vBO7m8lGbg" },
  { title: "Non-Polar Solvent — Petrol", url: "https://www.youtube.com/shorts/rAuf0RvhOSU" },
  { title: "Working of a Touch Screen (Electric Field)", url: "https://www.youtube.com/shorts/olKEZQ9v50g" },
  { title: "AC Current — Alternating Current", url: "https://www.youtube.com/shorts/OjZ0vxX-580" },
  { title: "Plasma Ball", url: "https://www.youtube.com/shorts/D6AHIi0S65w" },
  { title: "Light Refraction — Convex Lens", url: "https://www.youtube.com/shorts/ka4XG33n6ic" },
  { title: "Law of Inertia — First Law of Motion", url: "https://www.youtube.com/shorts/ZxNZm678A54" },
  { title: "Plasma Ball Experiment", url: "https://www.youtube.com/shorts/x-FJiYmhWYE" },
  { title: "Plasma Experiment — Physics", url: "https://www.youtube.com/shorts/BGJXJZ4jOTk" },
  { title: "Eddy Current", url: "https://www.youtube.com/shorts/48BiFQoJ2Sk" },
  { title: "Non-Polar Solvent — Petrol (Class 11)", url: "https://www.youtube.com/shorts/M02lqYTtNYo" },
  { title: "Mentos + Coke Experiment", url: "https://www.youtube.com/shorts/Uex4P4jj6ow" },
  { title: "Sodium is Highly Reactive", url: "https://www.youtube.com/shorts/g7hKF0yyV2M" },
  { title: "Capacitor Experiment", url: "https://www.youtube.com/shorts/JrKFZu5GEQw" },
  { title: "Critical Angle", url: "https://www.youtube.com/shorts/B6MoTUiD9CY" },
  { title: "Scattering of Light", url: "https://www.youtube.com/shorts/R1SG3e4x7DY" },
];